name: Android pipeline

on:
  push:
    branches:
      - main
    paths:
      - android/**
      - .github/workflows/cd-android.yml

jobs:
  commit-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: sleep 10 && echo "Android test done!"
  acceptance-cycle:
    needs: [commit-cycle]
    concurrency: acceptance-cycle
    name: Acceptance cycle
    uses: ./.github/workflows/acceptance-cycle.yml
  release-cycle:
    needs: [commit-cycle, acceptance-cycle]
    concurrency: release-cycle
    name: Release cycle
    uses: ./.github/workflows/release-cycle.yml
