name: iOS pipeline

on:
  push:
    branches:
      - main
    paths:
      - ios/**
      - .github/workflows/cd-ios.yml

jobs:
  commit-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: sleep 5 && echo "iOS test done!"
  acceptance-cycle:
    needs: [commit-cycle]
    concurrency:
      group: acceptance-cycle
      cancel-in-progress: false
    name: Acceptance cycle
    uses: ./.github/workflows/acceptance-cycle.yml
  release-cycle:
    needs: [commit-cycle, acceptance-cycle]
    concurrency:
      group: release-cycle
      cancel-in-progress: false
    name: Release cycle
    uses: ./.github/workflows/release-cycle.yml
