name: All platforms

on:
  push:
    branches:
      - main

jobs:
  commit-cycle:
    name: Commit cycle
    uses: ./.github/workflows/commit-cycle.yml
  acceptance-cycle:
    needs: [commit-cycle-android, commit-cycle-ios, commit-cycle-flutter]
    concurrency:
      group: acceptance-cycle
      cancel-in-progress: false
    name: Acceptance cycle
    uses: ./.github/workflows/acceptance-cycle.yml
  release-cycle:
    needs:
      - commit-cycle-android
      - commit-cycle-ios
      - commit-cycle-flutter
      - acceptance-cycle
    concurrency:
      group: release-cycle
      cancel-in-progress: false
    name: Release cycle
    uses: ./.github/workflows/release-cycle.yml
