name: All platforms

on:
  push:
    branches:
      - main

jobs:
  commit-cycle:
    name: Commit cycle
    uses: ./.github/workflows/commit-cycle.yml
  acceptance-cycle:
    needs: commit-cycle
    concurrency:
      group: acceptance-cycle
      cancel-in-progress: false
    name: Acceptance cycle
    uses: ./.github/workflows/acceptance-cycle.yml
  release-cycle:
    needs: [acceptance-cycle, commit-cycle]
    concurrency:
      group: release-cycle
      cancel-in-progress: false
    name: Release cycle
    uses: ./.github/workflows/release-cycle.yml
