name: Release Train

on: workflow_dispatch

jobs:
  generate_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: cd driver && flutter pub get
      - run:  cd driver &&flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: driver/build/app/outputs/apk/release/app-release.apk
