name: Release-cycle

on:
  workflow_call:

jobs:
  ios:
    runs-on: ubuntu-latest
    steps:
      - name: Publish iOS App
        run: echo "Pushing iOS app"
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Android app
        run: echo "Pushing Android app"
  publish-results:
    runs-on: ubuntu-latest
    needs: [ios, android]
    steps:
      - name: Echo jobs statuses
        run: echo "${{ job.status }} ${{ join(needs.*.result, ' ') }}"
